dist: trusty

sudo: false

language: node_js

node_js:
  - 8 

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod

cache:
  directories:
    - $HOME/.npm

install:
  - CYPRESS_INSTALL_BINARY=0 npm i
  - npm i firebase-ci@^0.5.0 # install deps used in creating config and deploying

script:
  
  - npm run lint
  - npm run test
  - npm run build

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: $HEROKU_APP
