export const LIST_PATH = '/projects'
export const ACCOUNT_PATH = '/account'
export const LOGIN_PATH = '/login'
export const SIGNUP_PATH = '/signup'
export const SELLING_POST_PATH = '/sellingpost'
export const POST_LIST_PATH = '/posts'
